Traceback (most recent call last):
  File "main.py", line 41, in <module>
    checkpoint_FUSEConv()
  File "main.py", line 18, in checkpoint_FUSEConv
    out = model(input_tensor)
  File "C:\Users\dhruvlaad\anaconda3\envs\minerl\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\IIT\Coursework\SysDL\CS6886\A6\fuseconv.py", line 81, in forward
    x = checkpoint.checkpoint(self.ckpt_forward_pass(*block_3, self.conv1, self.avg_pool, self.conv2), x)
TypeError: ckpt_forward_pass() argument after * must be an iterable, not FuseBlock
